### ISSUE TITLE
rails-example-project is now broken

### ISSUE THREAD

**Issue by zshuzh** [docker-hy/material-applications#2]
I'm doing the DevOps with Docker course, and was following along with Part 1: Technology agnostic. This part consists of creating a Dockerfile for the rails-example-project, but the image build failed with this error: 

`ERROR:  Could not find a valid gem 'mimemagic' (= 0.3.5) in any repository`

A Google search found this [StackOverflow](https://stackoverflow.com/questions/66919504/your-bundle-is-locked-to-mimemagic-0-3-5-but-that-version-could-not-be-found) post. Apparently, a week ago, the mimemagic versions were yanked. As suggested in one of the responses, deleting `Gemfile.lock` and bundling again worked for me.

**Comment by Jakousa** [comment]
Should be fixed by https://github.com/docker-hy/material-applications/commit/8f70d4e88d18979e86d9213b6d0b8b485471990e
